# Random

This is a space to put random problems to solve out of curiousity or practice.

### Problem 1
Given a list of timestamps in sequential order, return a list of lists grouped by week (7 days) using the first timestamp as the starting point.

Example:   

ts = [
    '2019-01-01', 
    '2019-01-02',
    '2019-01-08', 
    '2019-02-01', 
    '2019-02-05',
]

output = [
    ['2019-01-01', '2019-01-02'], 
    ['2019-01-08'], 
    ['2019-02-01', '2019-02-05'],
]

In [20]:
import pandas as pd
from datetime import date, timedelta

dates = pd.read_csv('data/dates.txt')

dates['date'] = pd.to_datetime(dates['date'], format='%Y-%m-%d')
dates['date'] = dates['date'].dt.date
print(dates.shape)
dates.head()

(351, 1)

         date
0  2018-01-06
1  2018-01-07
2  2018-01-11
3  2018-01-16
4  2018-01-20

In [33]:
week_end = dates['date'][0] + timedelta(days=7)
all_weeks = []
weekly = []

for d in dates['date']:
    if d < week_end:
        weekly.append(d.strftime('%Y-%m-%d'))
    elif d > week_end:
        week_end += timedelta(days=7)
        all_weeks.append(weekly)
        weekly = []
all_weeks

[['2018-01-06', '2018-01-07', '2018-01-11'],
 [],
 ['2018-01-22', '2018-01-23', '2018-01-25'],
 ['2018-01-30', '2018-02-02'],
 ['2018-02-06', '2018-02-09'],
 ['2018-02-15', '2018-02-16'],
 ['2018-02-22', '2018-02-23'],
 ['2018-02-27', '2018-03-02'],
 ['2018-03-05', '2018-03-06', '2018-03-09'],
 ['2018-03-12', '2018-03-13', '2018-03-14', '2018-03-16'],
 ['2018-03-19', '2018-03-20', '2018-03-23'],
 ['2018-03-26', '2018-03-27', '2018-03-28'],
 ['2018-04-02', '2018-04-03', '2018-04-05', '2018-04-06'],
 ['2018-04-09', '2018-04-10', '2018-04-13'],
 ['2018-04-16', '2018-04-17'],
 ['2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27'],
 ['2018-04-30', '2018-05-01', '2018-05-03', '2018-05-04'],
 ['2018-05-07', '2018-05-08', '2018-05-11'],
 ['2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17'],
 ['2018-05-21', '2018-05-22', '2018-05-25'],
 ['2018-05-28', '2018-05-29', '2018-06-01'],
 ['2018-06-04', '2018-06-05', '2018-06-08'],
 ['2018-06-11', '2018-06-12', '2018-06-14', '2018-06-15'],
 ['2018-06-18', '2018-06-19', '2018-06-22'],
 ['2018-06-25', '2018-06-26', '2018-06-28', '2018-06-29'],
 ['2018-07-06'],
 ['2018-07-09', '2018-07-10', '2018-07-12', '2018-07-13'],
 ['2018-07-16', '2018-07-17'],
 ['2018-07-23', '2018-07-24', '2018-07-26', '2018-07-27'],
 ['2018-07-30', '2018-07-31', '2018-08-02', '2018-08-03'],
 ['2018-08-06', '2018-08-07', '2018-08-09', '2018-08-10'],
 ['2018-08-13', '2018-08-14', '2018-08-16', '2018-08-17'],
 ['2018-08-20', '2018-08-21', '2018-08-23', '2018-08-24'],
 ['2018-08-27', '2018-08-28', '2018-08-30', '2018-08-31'],
 ['2018-09-03', '2018-09-04', '2018-09-06', '2018-09-07'],
 ['2018-09-11', '2018-09-13', '2018-09-14'],
 ['2018-09-17', '2018-09-18', '2018-09-19', '2018-09-21'],
 ['2018-09-24', '2018-09-25', '2018-09-26', '2018-09-27', '2018-09-28'],
 ['2018-10-02', '2018-10-03', '2018-10-04', '2018-10-05'],
 ['2018-10-08', '2018-10-11', '2018-10-12'],
 ['2018-10-15', '2018-10-17', '2018-10-18', '2018-10-19'],
 ['2018-10-22', '2018-10-23', '2018-10-25', '2018-10-26'],
 ['2018-10-29', '2018-10-30', '2018-11-02'],
 ['2018-11-05', '2018-11-06', '2018-11-09'],
 [],
 ['2018-11-21', '2018-11-22'],
 ['2018-11-26', '2018-11-27', '2018-11-29', '2018-11-30'],
 ['2018-12-03', '2018-12-04', '2018-12-07'],
 ['2018-12-11', '2018-12-13', '2018-12-14'],
 ['2018-12-17'],
 ['2018-12-24'],
 ['2019-01-03'],
 ['2019-01-11'],
 ['2019-01-14', '2019-01-15', '2019-01-16', '2019-01-18'],
 [],
 ['2019-01-29', '2019-02-01'],
 ['2019-02-04', '2019-02-05', '2019-02-07', '2019-02-08'],
 ['2019-02-11', '2019-02-12', '2019-02-14', '2019-02-15'],
 ['2019-02-19', '2019-02-22'],
 ['2019-02-28'],
 ['2019-03-04', '2019-03-05', '2019-03-06', '2019-03-07', '2019-03-08'],
 ['2019-03-12', '2019-03-14', '2019-03-15'],
 ['2019-03-18', '2019-03-19', '2019-03-21'],
 ['2019-03-25', '2019-03-26', '2019-03-28', '2019-03-29'],
 ['2019-04-02', '2019-04-04'],
 ['2019-04-11', '2019-04-12'],
 ['2019-04-16', '2019-04-18'],
 ['2019-04-22', '2019-04-23', '2019-04-25', '2019-04-26'],
 ['2019-04-29', '2019-04-30', '2019-05-02', '2019-05-03'],
 ['2019-05-06', '2019-05-07', '2019-05-09'],
 ['2019-05-14', '2019-05-16', '2019-05-17'],
 ['2019-05-21', '2019-05-23', '2019-05-24'],
 ['2019-05-30', '2019-05-31']]